# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pseudobry
description: > # this means to ignore newlines until "baseurl:"
  Husband. Father. Software Engineer. Open Source Hacker. Always Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.pseudobry.com" # the base hostname & protocol for your site
twitter_username: jmdobry
github_username: jmdobry
linkedin_username: jmdobry

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

# Outputting
permalink: /:title/
paginate: 5
paginate_path: /page/:num/
